language: java
jdk:
  - openjdk11
services:
  - docker
env:
  global:
    secure:$DOCKER_PASSWORD
    secure:$DOCKER_USERNAME
    secure:$HEROKU_API_KEY
    secure:$HEROKU_LOGIN
    secure:$HEROKU_APP
# replace the following env configurations with your own
before_install:
  - docker pull openjdk:11
  - cd API/curso_udemy_spring/
  - echo "We are in the Docker folder!!!"
#Build SpringBoot
script:
  - mvn clean package
# Create Docker image for our app and push it to Dockerhub repository and send messages to the Teams channel after the `script` job is successfully executed
after_success:
  - cd /home/travis/build/ronaldoalm/rest_api_spring_boot_udemy/API/
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker-compose build
  - docker push ronaldoalm1812/api-spring-boot:latest;
# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_APP
  on:
    tags: true
    repo: ronaldoalm1812/api-spring-boot